// using NLog;

namespace DaystarPaymentGateway
{
    public static partial class FirstDataAccess
    {
        //private static readonly Logger Logger = LogManager.GetLogger("NLogWriter");

        public static ResponseCode ComputeResponseCode(long id, string responseCode, string message, bool isApproved = false)
        {
            //Logger.Info($"ComputeResponseCode for DPG ID [{id}]: Processor [FirstData] | ResponseCode [{responseCode}] | Message [{message}] | IsApproved [{isApproved}]");

            if (isApproved)
                return ResponseCode.Approved;

            switch (responseCode)
            {
                case "000":
                    return ResponseCode.DeclinedNoAnswer;
                case "100":
                    return ResponseCode.Approved;
                case "109":
                    return ResponseCode.ApprovedPreviously;
                case "200":
                case "503":
                    return ResponseCode.DeclinedFraud;
                case "201":
                case "591":
                    return ResponseCode.DeclinedInvalidCreditCardNumber;
                case "202":
                case "203":
                case "205":
                case "592":
                    return ResponseCode.DeclinedInvalidAmount;
                case "204":
                    return ResponseCode.DeclinedOtherError;
                case "225":
                    return ResponseCode.DeclinedInvalidFieldData;
                case "227":
                    return ResponseCode.DeclinedMissingCompanionData;
                case "231":
                    return ResponseCode.DeclinedInvalidDivisionNumber;
                case "238":
                case "420":
                    return ResponseCode.DeclinedInvalidCurrency;
                case "239":
                    return ResponseCode.DeclinedInvalidMethodOfPaymentForDivision;
                case "241":
                    return ResponseCode.DeclinedIllegalAction;
                case "242":
                    return ResponseCode.DeclinedInvalidTemporaryServicesData;
                case "243":
                    return ResponseCode.DeclinedInvalidPurchaseLevel3;
                case "244":
                    return ResponseCode.DeclinedInvalidEncryptionFormat;
                case "245":
                    return ResponseCode.DeclinedMissingOrInvalidSecurePaymentData;
                case "246":
                    return ResponseCode.DeclinedMerchantMasterCardSecureCodeNotEnabled;
                case "248":
                    return ResponseCode.DeclinedBlanksNotPassedInReservedField;
                case "249":
                    return ResponseCode.DeclinedInvalidMerchantCategory;
                case "253":
                    return ResponseCode.DeclinedInvalidTransactionType;
                case "254":
                case "255":
                case "260":
                case "268":
                case "269":
                case "270":
                case "271":
                case "273":
                case "766":
                    return ResponseCode.DeclinedReserved;
                case "257":
                    return ResponseCode.DeclinedMissingCustomerServicePhone;
                case "258":
                    return ResponseCode.DeclinedNotAuthorizedToSendRecord;
                case "262":
                    return ResponseCode.DeclinedAuthorizationCodeResponseDateInvalid;
                case "263":
                    return ResponseCode.DeclinedPartialAuthorizationNotAllowed;
                case "264":
                case "299":
                case "551":
                case "776":
                    return ResponseCode.DeclinedDuplicateTransactionDetected;
                case "272":
                    return ResponseCode.DeclinedInvalidPurchaseLevel2;
                case "274":
                    return ResponseCode.DeclinedTransactionNotSupported;
                case "275":
                    return ResponseCode.DeclinedInvalidTime;
                case "276":
                    return ResponseCode.DeclinedInvalidDate;
                case "288":
                case "289":
                case "290":
                    return ResponseCode.DeclinedVelocityBlockReject;
                case "291":
                case "292":
                case "293":
                case "294":
                case "295":
                case "296":
                case "297":
                case "298":
                    return ResponseCode.DeclinedDisbursementReject;
                case "301":
                    return ResponseCode.DeclinedIssuerUnavailable;
                case "302":
                    return ResponseCode.DeclinedCreditFloor;
                case "303":
                    return ResponseCode.DeclinedProcessorDecline;
                case "304":
                    return ResponseCode.DeclinedNotOnFile;
                case "305":
                    return ResponseCode.DeclinedAlreadyReversed;
                case "306":
                    return ResponseCode.DeclinedAmountMismatch;
                case "307":
                    return ResponseCode.DeclinedAuthorizationNotFound;
                case "351":
                    return ResponseCode.DeclinedTransArmorServiceUnavailable;
                case "352":
                    return ResponseCode.DeclinedExpiredLock;
                case "353":
                    return ResponseCode.DeclinedTransArmorInvalidToken;
                case "354":
                    return ResponseCode.DeclinedTransArmorInvalidResult;
                case "401":
                case "402":
                    return ResponseCode.DeclinedCallVoiceOperator;
                case "501":
                    return ResponseCode.DeclinedPickup;
                case "502":
                    return ResponseCode.DeclinedLostStolenCard;
                case "506":
                    return ResponseCode.DeclinedInvalidInstitution;
                case "508":
                    return ResponseCode.DeclinedExcessivePINTry;
                case "509":
                    return ResponseCode.DeclinedOverTheLimit;
                case "510":
                    return ResponseCode.DeclinedOverLimitFrequency;
                case "519":
                    return ResponseCode.DeclinedOnNegativeFile;
                case "521":
                    return ResponseCode.DeclinedInsufficientFunds;
                case "522":
                case "903":
                    return ResponseCode.DeclinedExpiredCard;
                case "530":
                    return ResponseCode.DeclinedDoNotHonor;
                case "531":
                    return ResponseCode.DeclinedInvalidSecurityCode;
                case "546":
                    return ResponseCode.DeclinedBlockedAccount;
                case "570":
                    return ResponseCode.DeclinedStopPaymentOrderOneTimeRecurring;
                case "571":
                    return ResponseCode.DeclinedRevocationOfAuthorizationForAllRecurring;
                case "572":
                    return ResponseCode.DeclinedRevocationAllAuthorizations;
                case "580":
                    return ResponseCode.DeclinedAccountPreviouslyActivated;
                case "581":
                    return ResponseCode.DeclinedUnableToVoid;
                case "582":
                case "583":
                case "588":
                    return ResponseCode.DeclinedBlockActivationFailed;
                case "584":
                    return ResponseCode.DeclinedIssuanceDoesNotMeetMinimumAmount;
                case "585":
                    return ResponseCode.DeclinedNoOriginalAuthorizationFound;
                case "586":
                    return ResponseCode.DeclinedOutstandingAuthorization;
                case "587":
                    return ResponseCode.DeclinedActivationAmountIncorrect;
                case "589":
                    return ResponseCode.DeclinedInvalidSecurityCode;
                case "590":
                    return ResponseCode.DeclinedMaximumRedemptionLimitMet;
                case "594":
                    return ResponseCode.DeclinedOtherError;
                case "595":
                    return ResponseCode.DeclinedNewCardIssued;
                case "596":
                    return ResponseCode.DeclinedFraud;
                case "602":
                    return ResponseCode.DeclinedInvalidInstitutionCode;
                case "603":
                    return ResponseCode.DeclinedInvalidInstitution;
                case "606":
                    return ResponseCode.DeclinedInvalidTransactionType;
                case "607":
                    return ResponseCode.DeclinedInvalidAmount;
                case "610":
                    return ResponseCode.DeclinedBINBlock;
                case "740":
                    return ResponseCode.DeclinedMatchFailed;
                case "741":
                    return ResponseCode.DeclinedValidationFailed;
                case "750":
                    return ResponseCode.DeclinedReserved;
                case "752":
                    return ResponseCode.DeclinedMissingName;
                case "753":
                    return ResponseCode.DeclinedInvalidAccountType;
                case "754":
                    return ResponseCode.DeclinedAccountClosed;
                case "755":
                case "818":
                case "825":
                    return ResponseCode.DeclinedAccountNotFound;
                case "758":
                    return ResponseCode.DeclinedAccountFrozen;
                case "760":
                    return ResponseCode.DeclinedACHNonParticipant;
                case "763":
                    return ResponseCode.DeclinedInvalidAccountNumber;
                case "768":
                    return ResponseCode.DeclinedBadAccountNumberData;
                case "777":
                    return ResponseCode.DeclinedOriginalTransactionNotApproved;
                case "787":
                    return ResponseCode.DeclinedHighRisk;
                case "788":
                    return ResponseCode.DeclinedRefundGreaterThanOriginal;
                case "802":
                    return ResponseCode.DeclinedFurtherInformationNeeded;
                case "806":
                    return ResponseCode.DeclinedCardRestricted;
                case "811":
                case "842":
                    return ResponseCode.DeclinedInvalidSecurityCode;
                case "813":
                    return ResponseCode.DeclinedInvalidPIN;
                case "833":
                    return ResponseCode.DeclinedInvalidMerchant;
                case "834":
                    return ResponseCode.DeclinedUnauthorizedUser;
                case "902":
                    return ResponseCode.DeclinedProcessUnavailable;
                case "904":
                    return ResponseCode.DeclinedCardInactive;
                case "997":
                    return ResponseCode.DeclinedAcquirerError;
                default:
                    return ResponseCode.ErrorUnrecognizedResponseCode;
            }
        }
    }
}
